### ISSUE TITLE
Bug  RPOA_google < OPT

### ISSUE THREAD

**Issue by majid-khonji** [majid-khonji/rent-or-buy#1]
Run the following multiple times, CR < 1

w = 0.9
ins = i.Instance(predictor_std=5, time_dependant=True); rsol = ag.RPOA_google(ins, w); opt = a.OPT(ins); rsol/opt

Another issue is when w = 0.999: RPOA_google returns an error.

**Comment by Yue-Zhou1** [comment]
fixed

**Comment by Yue-Zhou1** [comment]
fixed
